<?php

/**
 * This file is part of the Yii2 extension module, yii2-visitor
 *
 * @author John Snook
 * @date 2018-06-28
 * @license https://github.com/johnsnook/yii2-visitor/LICENSE
 * @copyright 2018 John Snook Consulting
 */

namespace johnsnook\visitor\models;

use yii\base\Model;
use yii\data\ActiveDataProvider;
use johnsnook\visitor\models\VisitorLog;
use johnsnook\parsel\ParselQuery;

/**
 * VisitorLogSearch represents the model behind the search form of `common\models\VisitorLog`.
 */
class VisitorLogSearch extends VisitorLog {

    /**
     * @var string Virtual field to pass user query for yii2-parsel
     */
    public $userQuery;

    /**
     * @var string Any parser errors that may have occurred
     */
    public $queryError;

    /**
     * @var string The sql string generated by ParselQuery. For debugging purposes
     */
    public $sql;

    /**
     * @var array The fields to search with ParselQuery
     */
    private $fields = ['request', 'referer', 'user_agent'];

    /**
     * {@inheritdoc}
     */
    public function rules() {
        return [
            [['id'], 'integer'],
            [['ip', 'userQuery'], 'safe'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function scenarios() {
        // bypass scenarios() implementation in the parent class
        return Model::scenarios();
    }

    /**
     * Creates data provider instance with search query applied
     *
     * @param array $params
     *
     * @return ActiveDataProvider
     */
    public function search($params) {
        $this->load($params);

        $parsel = new ParselQuery([
            'userQuery' => $this->userQuery,
            'searchFields' => $this->fields,
            'dbQuery' => VisitorLog::find()->where(['ip' => $this->ip])
        ]);


        $dataProvider = new ActiveDataProvider([
            'query' => $parsel->dbQuery,
            'pagination' => [
                'pageSize' => 20,
            ],
            'sort' => [
                'defaultOrder' => [
                    'created_at' => SORT_DESC,
                ]
            ],
        ]);

        return $dataProvider;
    }

}
